#공통 설정
spring:
  # profiles
  profiles:
    default: local
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  messages:
    cache-duration: -1
    basename: messages/message
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  config: classpath:log4j2.yml

#===================local server===================
---
server:
  port: 18080
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ENC(v0wdL0P0VUbR4SWl3SVjUU2h9BO3yhCBIMw0HlACGqutWqnQt3l/DVZZxuGI254+kT3sV0SOoGg+wjpWkEAMnflv0FtKxGxdjA+PCAX2VVHWbKDSoBqZUwY5avVslPxe3PXKUJAOdWfQ7Bbp4UE2kp/y9XJxniWaFYSD6htTC9XlEnAbSMfnLOXzPv89ZAlW)
    username: ENC(SEALWx3gBGg525YEKIVmQA==)
    password: ENC(ypeuuLZsd3hBE5tXtEZK/g==)

#===================prod server===================
---
server:
  port: 18080
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ENC(zMBfwwoa6JO3PunRBPynfHABO8skHvY0N4eDrbK8rEGqxGMsHtScYbJIGlxatEl/TU9QCGrLlA80LR76+OHnPuslApkGTrIbYzz0Na1ubl8d9CboQCoJi+KLzd2aTLApZBOToqbCJTB/R/NvbdtazkyMeaHPbcBlC0foskYN48/oVTjSFhMybi5EyC3virNm)
    username: ENC(Ojjh12KU0wasDf9l0zb9MQ==)
    password: ENC(VmVkegQnmEJr9rVmNAkcJjW8AjfDh0da)